# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: replacetokens@4
  displayName: 'Replace tokens in appsettings.json'
  inputs:
    rootDirectory: '$(build.sourcesdirectory)/src/MyHealth.Web'
    targetFiles: appsettings.json
    escapeType: none

- task: replacetokens@3
  displayName: 'Replace tokens in mhc-aks.yaml'
  inputs:
    targetFiles: 'mhc-aks.yaml'
    escapeType: none
    tokenPrefix: '__'
    tokenSuffix: '__'

- task: DockerCompose@0
  displayName: 'Run services'
  inputs:
    containerregistrytype: 'Azure Container Registry'
    azureSubscription: azureSubscription:'Azure subscription 1 (b61f6c78-544f-48ad-9479-7728a6292de3)'
    azureContainerRegistry: '{"loginServer":"segunyumaacr324.azurecr.io", "id" : "/subscriptions/b61f6c78-544f-48ad-9479-7728a6292de3/resourceGroups/akshandsonlab/providers/Microsoft.ContainerRegistry/registries/segunyumaacr324"}'
    dockerComposeFile: 'docker-compose.ci.build.yml'
    action: 'Run services'
    detached: false

- task: DockerCompose@0
  displayName: 'Build services'
  inputs:
    containerregistrytype: 'Azure Container Registry'
    azureSubscription: 'Azure subscription 1 (b61f6c78-544f-48ad-9479-7728a6292de3)'
    azureContainerRegistry: '{"loginServer":"segunyumaacr324.azurecr.io", "id" : "/subscriptions/b61f6c78-544f-48ad-9479-7728a6292de3/resourceGroups/akshandsonlab/providers/Microsoft.ContainerRegistry/registries/segunyumaacr324"}'
    dockerComposeFile: 'docker-compose.yml'
    dockerComposeFileArgs: 'DOCKER_BUILD_SOURCE='
    action: 'Build services'
    additionalImageTags: '$(Build.BuildId)'

- task: DockerCompose@0
  displayName: 'Push services'
  inputs:
    containerregistrytype: 'Azure Container Registry'
    azureSubscription: 'Azure subscription 1 (b61f6c78-544f-48ad-9479-7728a6292de3)'
    azureContainerRegistry: '{"loginServer":"segunyumaacr324.azurecr.io", "id" : "/subscriptions/b61f6c78-544f-48ad-9479-7728a6292de3/resourceGroups/akshandsonlab/providers/Microsoft.ContainerRegistry/registries/segunyumaacr324"}'
    dockerComposeFile: 'docker-compose.yml'
    dockerComposeFileArgs: 'DOCKER_BUILD_SOURCE='
    action: 'Push services'
    additionalImageTags: '$(Build.BuildId)'

- task: DockerCompose@0
  displayName: 'Lock services'
  inputs:
    containerregistrytype: 'Azure Container Registry'
    azureSubscription: 'Azure subscription 1 (b61f6c78-544f-48ad-9479-7728a6292de3)'
    azureContainerRegistry: '{"loginServer":"segunyumaacr324.azurecr.io", "id" : "/subscriptions/b61f6c78-544f-48ad-9479-7728a6292de3/resourceGroups/akshandsonlab/providers/Microsoft.ContainerRegistry/registries/segunyumaacr324"}'
    dockerComposeFile: 'docker-compose.yml'
    dockerComposeFileArgs: 'DOCKER_BUILD_SOURCE='
    action: 'Lock services'
    outputDockerComposeFile: '$(Build.StagingDirectory)/docker-compose.yml'

- task: CopyFiles@2
  displayName: 'Copy Files'
  inputs:
    Contents: |
     **/mhc-aks.yaml
     **/*.dacpac
     
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    ArtifactName: deploy

- task: Wait@1
  inputs:
    Value: '60'
    Unit: 'seconds'

# release


- task: SqlAzureDacpacDeployment@1
  displayName: 'Azure SQL DacpacTask' 
  inputs:
    azureSubscription: 'Azure subscription 1 (b61f6c78-544f-48ad-9479-7728a6292de3)'
    ServerName: '$(SQLserver)'
    DatabaseName: '$(databasename)'
    SqlUsername: '$(SQLuser)'
    SqlPassword: '$(SQLpassword)'
    DacpacFile: '$(System.DefaultWorkingDirectory)/_MyHealth-AKS.Build/drop/myhealthclinic.dacpac'
